name = "meshsdk/aiken-template"
version = "0.0.0"
compiler = "v1.1.3"
plutus = "v2"
license = "Apache-2.0"
description = "Aiken contracts for project 'meshsdk/aiken-template'"

[repository]
user = "meshsdk"
project = "aiken-template"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.1.1-beta"
source = "github"

[config]
